Call abs on arity when extracting reload
* Optional arguments in the method signature cause arity to be a
  negative number. Call abs on the method arity to fix option values not
  working and throwing something like:

  ArgumentError:   wrong number of arguments (3 for 2)